---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  attributes:
    authorization:
      sudo:
        users:
          - centos

platforms:
  - name: centos-6.6
    driver_plugin: openstack
    driver_config:
        username: centos
        image_ref: "CentOS 6.6"
    attributes:
        pgd:
            pgd_path: "/opt/pgd"
            virtualenv_path: "/opt/vrt"
            user: "centos"
            group: "centos"

suites:
  - name: cloud
    run_list:
      - recipe[pgd_cookbook::default]
      - recipe[pgd_cookbook::bootstrap_user]

