name                'pgd_cookbook'
maintainer          'OSU Open Source Lab'
maintainer_email    'chef@osuosl.org'
license             'Apache v2'
description         'Installs/Configures pgd_cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'

depends          'apache2'
depends          'build-essential'
depends          'database'
depends          'git'
depends          'mysql'
depends          'postgresql'
depends          'python'
depends          'yum'
depends          'yum-epel'
depends          'yum-ius'
depends          'yum-osuosl'
